language: php

php:
  - 7.0
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_install: ci/travis/before_install.sh
install: ci/travis/install.sh
script: ci/travis/script.sh

notifications:
  webhook:
    secure: "owlXxH0Ckk8ko981trYdqfCmeXfH801mX3/fwznFvvuW/t/weVFM5hjp4mvHTGKrCFskLb7k3eojcDN+GCHEnRjVXBCC0fvFuUfx61A99h4v42ahYxl8iKCQN0UT+AtJaYa7Cs98s4PcTdge4tgq1pSroGeWbYdXsvkTSj/WzV5v8A1SFPb2dKbUeP+Ijj30GwVPM+4SYLaYdpeFE9WM5/VS+Cvdkfi2T6Zs7ysGKA1nZQ/geO+JRM0gdn08TRwcyyRxPMlrvCYWyn1oBx6UoUcR+Z8DNEZuIb/IwNLoo0bbE1FGN2jOo7pAberr5+i1AguFLfn+7ABt/Ugy7VPtjbHPkSKbz/0VsBxuJge1jhBpnbQf8BFE/9+JlCaAM1tVqUBGucF3MzqYDeBbzdo3lEUvhBf+3SfggxVvT6gokAjAiV7MchnnMACv9CIqXpUwLtokHitXwwWfhY8IU8ZMCOGklY1Chby/X+dvwc7upwU/mih8Jk+5AguY6xVSHNgpd75jYxsIdzKJ2t/mwbRSlWxCmD6Uz8T5q8k3MkM7X9kv7Bg/Wu2EPbXj6Q7CJGD9zyH4q5OyFQVZmldSy22e9+WTnDDC8vO94KvYB7FK4+WERWeVtFPDBw8qZAklsPhxsFCmzmriF97eFjoUW9cjxBj4khFkUo1IBpjRMuOEJgc="
