language: php

php:
  - 7.0
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_install: ci/travis/before_install.sh
install: ci/travis/install.sh
script: ci/travis/script.sh
