language: php

php:
  - 7.0
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_install: composer self-update
install: composer update --prefer-dist
script: phpunit
